theme: jekyll-theme-minimal
title: Rebecca W. Loraamm, PhD
description: Assistant Professor, University of Oklahoma Dept. of Geography and Environmental Sustainability
show_downloads: false
logo: ./images/Rebecca_Loraamm.jpg
