theme: jekyll-theme-minimal
title: Rebecca Whitehead Anderson, PhD
description: Assistant Professor, University of Oklahoma Dept. of Geography and Environmental Sustainability
show_downloads: false
logo: ./images/key_west_topo_2.jpg
